const ICOListData = [
  {
    id: 1,
    icon: <i className="fa-solid fa-bitcoin-sign"></i>,
    title: "Bitcoin",
    titlespan: "Finance",
    price: "$79/90",
    interest: "50%",
    pricespan: "Neutral",
    date: "Ended 12 oct",
  },
  {
    id: 2,
    icon: <i className="fa-solid fa-litecoin-sign"></i>,
    title: "Litecoin",
    titlespan: "Infrastructure",
    price: "$72/100.00",
    interest: "80%",
    pricespan: "Neutral",
    date: "Ended 20 Oct",
  },
  {
    id: 3,
    icon: <i className="fa-brands fa-ethereum"></i>,
    title: "Etherium",
    titlespan: "Construction",
    price: "$30/100.00",
    interest: "50%",
    pricespan: "Neutral",
    date: "Ended 25 Oct",
  },
  {
    id: 4,
    icon: <i className="fa-brands fa-monero"></i>,
    title: "Monero",
    titlespan: "Infrastructure",
    price: "$72/100.00",
    interest: "80%",
    pricespan: "Not Rated",
    date: "Ended 16 Oct",
  },
  {
    id: 5,
    icon: <i className="fa-brands fa-digital-ocean"></i>,
    title: "Cardano",
    titlespan: "Infrastructure",
    price: "$72/82",
    interest: "20%",
    pricespan: "Neutral",
    date: "15 Day Left",
  },
  {
    id: 6,
    icon: <i className="fa-brands fa-airbnb"></i>,
    title: "Ardor",
    titlespan: "Infrastructure",
    price: "$72/100.00",
    interest: "80%",
    pricespan: "Neutral",
    date: "9 Day Left",
  },
  {
    id: 7,
    icon: <i className="fa-brands fa-affiliatetheme"></i>,
    title: "OmiGO",
    titlespan: "Infrastructure",
    price: "$85/90",
    interest: "70%",
    pricespan: "Not Rated",
    date: "Ended 20 Oct",
  },
  {
    id: 8,
    icon: <i class="fa-brands fa-steam-symbol"></i>,
    title: "Tether",
    titlespan: "Infrastructure",
    price: "$72/100.00",
    interest: "80%",
    pricespan: "Not Rated",
    date: "Ended 25 Oct",
  },
  {
    id: 9,
    icon: <i class="fa-brands fa-korvue"></i>,
    title: "Komodo",
    titlespan: "Devolopment",
    price: "$72/100.00",
    interest: "80%",
    pricespan: "Neutral",
    date: "Ended 23 Oct",
  },
  {
    id: 10,
    icon: <i class="fa-solid fa-austral-sign"></i>,
    title: "Arc",
    titlespan: "Technology",
    price: "$82/100",
    interest: "70%",
    pricespan: "Not Rated",
    date: "Ended 27 Oct",
  },
  {
    id: 11,
    icon: <i class="fa-solid fa-biohazard"></i>,
    title: "Quantom",
    titlespan: "Future",
    price: "$75/100",
    interest: "80%",
    pricespan: "Science",
    date: "Ended 25 Oct",
  },
  {
    id: 12,
    icon: <i class="fa-solid fa-fan"></i>,
    title: "NEM",
    titlespan: "Infrastructure",
    price: "$72/100.00",
    interest: "80%",
    pricespan: "Neutral",
    date: "Ended 20 Oct",
  },
  {
    id: 13,
    icon: <i class="fa-brands fa-atlassian"></i>,
    title: "Augur",
    titlespan: "Manufacturing",
    price: "$90/100",
    interest: "85%",
    pricespan: "Not Rated",
    date: "Ended 20 Oct",
  },
  {
    id: 14,
    icon: <i class="fa-solid fa-atom"></i>,
    title: "Atoms",
    titlespan: "Technology",
    price: "$72/100",
    interest: "80%",
    pricespan: "Neutral",
    date: "Ended 20 Oct",
  },
  {
    id: 15,
    icon: <i class="fa-solid fa-layer-group"></i>,
    title: "Startis",
    titlespan: "Trading",
    price: "$72/100",
    interest: "80%",
    pricespan: "Neutral",
    date: "Ended 20 Oct",
  },
  {
    id: 16,
    icon: <i class="fa-solid fa-lari-sign"></i>,
    title: "Sango",
    titlespan: "Curruncy",
    price: "$65/100",
    interest: "99%",
    pricespan: "Neutral",
    date: "Ended 20 Oct",
  },
  {
    id: 17,
    icon: <i class="fa-solid fa-franc-sign"></i>,
    title: "Fragmint",
    titlespan: "Plateform",
    price: "$55/100",
    interest: "70%",
    pricespan: "Neutral",
    date: "Ended 20 Oct",
  },
  {
    id: 18,
    icon: <i class="fa-sharp fa-solid fa-copyright"></i>,
    title: "Crypcrade",
    titlespan: "Investment & Trading",
    price: "$50/100",
    interest: "75%",
    pricespan: "Neutral",
    date: "Ended 15 Oct",
  },
  {
    id: 19,
    icon: <i class="fa-brands fa-angular"></i>,
    title: "Ameta",
    titlespan: "Gaming",
    price: "$72/100",
    interest: "80%",
    pricespan: "Neutral",
    date: "Ended 10 Nov",
  },
  {
    id: 20,
    icon: <i class="fa-brands fa-phoenix-framework"></i>,
    title: "Moverse",
    titlespan: "Blockchain Service",
    price: "$30/100",
    interest: "80%",
    pricespan: "Neutral",
    date: "Ended 20 Nov",
  },
];

export default ICOListData;
